=== jgraber/ataraxis/application_data/config/ataraxis.dtd
<!ELEMENT ataraxis (group|account)*>
<!ELEMENT group (account)*>
<!ATTLIST group id ID #REQUIRED>
<!ELEMENT account (name?,password?,link?,comment?)>
<!ATTLIST account id ID #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT link (#PCDATA)>
<!ELEMENT comment (#PCDATA)>

=== jgraber/ataraxis/test/template.xml
<?xml version="1.0"?>
<!DOCTYPE ataraxis SYSTEM "./application_data/config/ataraxis.dtd">
<ataraxis>
 <account id="Z BFH Mail">
  <name>Graber</name>
  <password>PW BFH XCY</password>
 </account>
 <account id="A BFHMail_2">
  <name>Graber2</name>
  <password>PW BFH 2 XCY</password>
 </account>
 
 <group id="Mail">
  <account id="m_BFH">
  <name>Gr</name>
  <password>PW BBBBFFFFHHHH</password>
 </account>
   <account id="m_A BFH">
  <name>Gr</name>
  <password>PW BBBBFFFFHHHH</password>
 </account>
    <account id="m_zBFH">
  <name>Gr</name>
  <password>PW BBBBFFFFHHHH</password>
 </account>
 </group>
 
  <group id="Passwords">
  <account id="p_BFH">
  <name>Gr</name>
  <password>PW BBBBFFFFHHHH</password>
 </account>
   <account id="p_A BFH">
  <name>Gr</name>
  <password>PW BBBBFFFFHHHH</password>
 </account>
    <account id="p_zBFH">
  <name>Gr</name>
  <password>PW BBBBFFFFHHHH</password>
 </account>
 </group>
 
 <group id="Accounts">
  <account id="a_BFH">
  <name>Gr</name>
  <password>PW BBBBFFFFHHHH</password>
 </account>
   <account id="a_A BFH">
  <name>Gr</name>
  <password>PW BBBBFFFFHHHH</password>
 </account>
    <account id="a_zBFH">
  <name>Gr</name>
  <password>PW BBBBFFFFHHHH</password>
 </account>
 </group>
 
 
 <group id="ZZ Accountssssssssssssssssssssssssss">
  <account id="z_BFH">
  <name>Gr</name>
  <password>PW BBBBFFFFHHHH</password>
 </account>
   <account id="z_A BFH">
  <name>Gr</name>
  <password>PW BBBBFFFFHHHH</password>
 </account>
    <account id="z_zBFH">
  <name>Gr</name>
  <password>PW BBBBFFFFHHHH</password>
 </account>
 </group>
</ataraxis>
